/**
 * Grow a Garden (GAG) - Master Items Catalog
 * Enthält die vollständige Referenzliste aller Seeds und Gear-Items,
 * damit diese auch dann angezeigt werden können, wenn sie aktuell nicht im Stock sind (0 auf Lager).
 */

const MASTER_SEEDS = [
  "Cocomango",
  "Blueberry",
  "Broccoli",
  "Bamboo",
  "Carrot",
  "Buttercup",
  "Strawberry",
  "Tomato",
  "Corn",
  "Watermelon",
  "Pumpkin",
  "Apple",
  "Coconut",
  "Cactus",
  "Dragon Fruit",
  "Mango",
  "Grape",
  "Mushroom",
  "Pepper",
  "Cacao",
  "Lemon",
  "Pineapple",
  "Peach",
  "Pear",
  "Papaya",
  "Banana",
  "Passion Fruit",
  "Soul Fruit",
  "Cursed Fruit",
  "Chocolate Carrot",
  "Red Lollipop",
  "Candy Sunflower",
  "Easter Egg",
  "Candy Blossom",
  "Raspberry",
  "Cranberry",
  "Durian",
  "Eggplant",
  "Venus Fly Trap",
  "Lotus",
  "Glowshroom",
  "Mint",
  "Moonflower",
  "Starfruit",
  "Moonglow",
  "Moon Blossom",
  "Cherry Blossom",
  "Moon Melon",
  "Beanstalk",
  "Blood Banana",
  "Moon Mango",
  "Celestiberry",
  "Rose",
  "Foxglove",
  "Lilac",
  "Pink Lily",
  "Purple Dahila",
  "Nectarine",
  "Hive Fruit",
  "Sunflower",
  "Honeysuckle",
  "Lavender",
  "Manuka Flower",
  "Nectarshade",
  "Dandelion",
  "Lumira",
  "Ember Lily",
  "Feijoa",
  "Loquat",
  "Prickly Pear",
  "Bell Pepper",
  "Kiwi",
  "Avocado",
  "Green Apple",
  "Cauliflower",
  "Elephant Ears",
  "Rosy Delight",
  "Parasol Flower",
  "Cantaloupe",
  "Wild Carrot",
  "Pitcher Plant",
  "Traveler's Fruit",
  "Guanabana",
  "Lily Of The Valley",
  "Aloe Vera",
  "Rafflesia",
  "Peace Lily",
  "Delphinium",
  "Firework Flower",
  "Liberty Lily",
  "Sugar Apple",
  "Bone Blossom",
  "Burning Bud",
  "Fossilight",
  "Giant Pinecone",
  "Grand Volcania",
  "Amber Spine",
  "Lingonberry",
  "Horsetail",
  "Firefly Fern",
  "Boneboo",
  "Horned Dinoshroom",
  "Paradise Petal",
  "Stonebite",
  "Maple Apple",
  "Spiked Mango",
  "Hinomai",
  "Soft Sunshine",
  "Zen Rocks",
  "Zenflare",
  "Taro Flower",
  "Serenity",
  "Monoblooma",
  "Elder Strawberry",
  "Tranquil Bloom",
  "Enkaku",
  "Sakura Bush",
  "Lucky Bamboo",
  "Dezen",
  "Grand Tomato",
  "Tall Asparagus",
  "Taco Fern",
  "Sugarglaze",
  "Veinpetal",
  "Twisted Tangle",
  "Crown Melon",
  "Jalapeno",
  "Artichoke",
  "Onion",
  "King Cabbage",
  "Badlands Pepper",
  "Bitter Melon",
  "Pricklefruit",
  "Butternut Squash",
  "Spring Onion",
  "Rhubarb",
  "Romanesco",
  "Amberheart",
  "Princess Thorn",
  "Cyclamen",
  "Willowberry",
  "Snaparino Beanarini",
  "Calla Lily",
  "Flare Melon",
  "Glowpod",
  "Crown of Thorns",
  "Gleamroot",
  "Poseidon Plant",
  "Canary Melon",
  "Mandrake",
  "Duskpuff",
  "Flare Daisy",
  "Golden Egg",
  "Wispwing",
  "Aurora Vine",
  "Brussels Sprout",
  "Spirit Flower",
  "Briar Rose",
  "Potato",
  "Lightshoot",
  "Glowthorn",
  "Aetherfruit",
  "Urchin Plant",
  "Untold Bell",
  "Pyracantha",
  "Horned Melon",
  "Blue Raspberry",
  "Ackee",
  "Pixie Faern",
  "Emerald Bud",
  "Radish",
  "Maple Resin",
  "Golden Peach",
  "Mangrove",
  "Kniphofia",
  "Carnival Pumpkin",
  "Meyer Lemon",
  "Parsley",
  "Turnip",
  "Crimson Thorn",
  "Multitrap",
  "Naval Wort",
  "Inferno Quince",
  "Mandrone Berry",
  "Black Bat Flower",
  "Sundew",
  "Evo Beetroot",
  "Evo Blueberry",
  "Evo Pumpkin",
  "Evo Mushroom",
  "Acorn",
  "Persimmon",
  "Hazelnut",
  "Evo Apple",
  "Pecan",
  "Ferntail",
  "Acorn Squash",
  "Fissure Berry",
  "Great Pumpkin",
  "Poison Apple",
  "Seer Vine",
  "Chicken Feed",
  "Ghoul Root",
  "Jack O Lantern",
  "Bloodred Mushroom",
  "Banesberry",
  "Weeping Branch",
  "Blood Orange",
  "Mummy's Hand",
  "Wisp Flower",
  "Zombie Fruit",
  "Candy Cornflower",
  "Severed Spine",
  "Wereplant",
  "Devilroot",
  "Ghost Bush",
  "Glass Kiwi",
  "Spider Vine",
  "Monster Flower",
  "Trinity Fruit",
  "Thornspire",
  "Wyrmvine",
  "Ghost Pepper",
  "Buddhas Hand",
  "Baobab",
  "Viburnum Berry",
  "Protea",
  "Banana Orchid",
  "Orange Delight",
  "Horned Redrose",
  "Sunbulb",
  "Orange Tulip",
  "Daffodil"
];

const MASTER_GEARS = [
  "Watering Can",
  "Harvest Tool",
  "Trowel",
  "Recall Wrench",
  "Favorite Tool",
  "Pet Lead",
  "Pet Name Reroller",
  "Trading Ticket",
  "Basic Sprinkler",
  "Advanced Sprinkler",
  "Godly Sprinkler",
  "Master Sprinkler",
  "Grandmaster Sprinkler",
  "Lush Sprinkler",
  "Chocolate Sprinkler",
  "Honey Sprinkler",
  "Spice Spritzer Sprinkler",
  "Sweet Soaker Sprinkler",
  "Flower Froster Sprinkler",
  "Stalk Sprout Sprinkler",
  "Tropical Mist Sprinkler",
  "Berry Blusher Sprinkler",
  "Cleaning Spray",
  "Tanning Mirror",
  "Magnifying Glass",
  "Friendship Pot",
  "Star Caller",
  "Pollen Radar",
  "Nectar Staff",
  "Night Staff",
  "Corrupt Radar",
  "Tranquil Radar",
  "Super Leaf Blower",
  "Lightning Rod"
];

// Emoji-Fallbacks für schnelles Rendering, falls ein CDN-Bild lädt oder fehlt
const FALLBACK_EMOJIS = {
  seeds: "🌱",
  gear: "🛠️",
  cosmetics: "🎨"
};
